# Generated by Django 4.0.3 on 2022-03-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='post/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.category')),
            ],
        ),
    ]
